export enum PresenceEventTypes {
    JOIN = 'JOIN',
    LEAVE = 'LEAVE',
    UPDATE = 'UPDATE'
}

export enum ServerActions {
    PRESENCE = 'PRESENCE',
    SYSTEM = 'SYSTEM',
    BROADCAST = 'BROADCAST',
    ERROR = 'ERROR',
}

export enum ClientActions {
    JOIN_CHANNEL = 'JOIN_CHANNEL',
    LEAVE_CHANNEL = 'LEAVE_CHANNEL',
    BROADCAST = 'BROADCAST',
}

export enum ChannelState {
    IDLE = 'IDLE',
    JOINING = 'JOINING',
    JOINED = 'JOINED',
    STALLED = 'STALLED',
    CLOSED = 'CLOSED',
}

export enum ErrorTypes {
    UNAUTHORIZED_CONNECTION = 'UNAUTHORIZED_CONNECTION',
    UNAUTHORIZED_JOIN_REQUEST = 'UNAUTHORIZED_JOIN_REQUEST',
    UNAUTHORIZED_BROADCAST = 'UNAUTHORIZED_BROADCAST',
    INVALID_MESSAGE = 'INVALID_MESSAGE',
    HANDLER_NOT_FOUND = 'HANDLER_NOT_FOUND',
    PRESENCE_ERROR = 'PRESENCE_ERROR',
    CHANNEL_ERROR = 'CHANNEL_ERROR',
    ENDPOINT_ERROR = 'ENDPOINT_ERROR',
    INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
}

export enum SystemSender {
    ENDPOINT = 'ENDPOINT',
    CHANNEL = 'CHANNEL',
}

export enum ChannelReceiver {
    ALL_USERS = 'ALL_USERS',
    ALL_EXCEPT_SENDER = 'ALL_EXCEPT_SENDER',
}

export enum Events {
    ACKNOWLEDGE = 'ACKNOWLEDGE',
}
