from __future__ import annotations

from importlib.metadata import PackageNotFoundError, version

from pondsocket_common import (
    ChannelReceiver,
    Headers,
    IncomingConnection,
    JoinParams,
    PondAssigns,
    PondMessage,
    PondPresence,
    PresenceEventTypes,
    ServerActions,
    UserData,
    uuid,
)

from .channel import Channel, ChannelOptions
from .contexts import (
    ConnectionContext,
    ConnectionDecision,
    EventContext,
    JoinContext,
    LeaveContext,
    OutgoingContext,
)
from .endpoint import (
    ConnectionHandler,
    ConnectionMiddlewareFn,
    Endpoint,
    JoinHandler,
    JoinMiddlewareFn,
)
from .errors import (
    MultiError,
    PondError,
    bad_request,
    conflict,
    error_event,
    forbidden,
    internal,
    not_found,
    too_many_requests,
    unauthorized,
)
from .hooks import (
    AfterJoin,
    AfterMessage,
    BeforeJoin,
    BeforeMessage,
    Hooks,
    MetricsCollector,
    NoopMetrics,
    OnConnect,
    OnDisconnect,
    RateLimiter,
    TokenBucketRateLimiter,
    with_metrics,
    with_rate_limiter,
)
from .in_memory_transport import InMemoryTransport
from .lobby import EventHandler, EventMiddlewareFn, LeaveHandler, Lobby, OutgoingHandler
from .middleware import Middleware
from .parser import parse
from .presence import PresenceClient
from .pubsub import (
    PubSub,
    PubSubClosedError,
    format_heartbeat_topic,
    format_message_topic,
    format_presence_topic,
    format_system_topic,
    format_topic,
    match_topic,
)
from .pubsub_local import LocalPubSub
from .server import EndpointMatch, PondSocket
from .sse_transport import SSEServerTransport
from .store import Store
from .transport import OnCloseCallback, OnMessageHandler, PushableTransport, Transport
from .typed import (
    TypedChannel,
    TypedEventContext,
    TypedEventHandler,
    TypedJoinContext,
    TypedJoinHandler,
    TypedLobby,
    typed_lobby,
)
from .types import (
    AllExceptSender,
    AllUsers,
    DistributedMessageType,
    Event,
    InternalActions,
    LeaveReason,
    MessageEvent,
    Options,
    RecipientSpec,
    Route,
    SystemEntity,
    SystemEvents,
    ToUsers,
    TransportType,
    User,
)
from .wire import (
    event_to_json,
    event_to_pubsub_bytes,
    event_to_wire,
    parse_inbound_text,
    pubsub_bytes_to_event,
    wire_to_event,
)

try:
    __version__ = version("pondsocket")
except PackageNotFoundError:
    __version__ = "0.0.1"

__all__ = [
    "AfterJoin",
    "AfterMessage",
    "AllExceptSender",
    "AllUsers",
    "BeforeJoin",
    "BeforeMessage",
    "Channel",
    "ChannelOptions",
    "ChannelReceiver",
    "ConnectionContext",
    "ConnectionDecision",
    "ConnectionHandler",
    "ConnectionMiddlewareFn",
    "DistributedMessageType",
    "Endpoint",
    "EndpointMatch",
    "Event",
    "EventContext",
    "EventHandler",
    "EventMiddlewareFn",
    "Headers",
    "Hooks",
    "InMemoryTransport",
    "IncomingConnection",
    "InternalActions",
    "JoinContext",
    "JoinHandler",
    "JoinMiddlewareFn",
    "JoinParams",
    "LeaveContext",
    "LeaveHandler",
    "LeaveReason",
    "Lobby",
    "LocalPubSub",
    "MessageEvent",
    "MetricsCollector",
    "Middleware",
    "MultiError",
    "NoopMetrics",
    "OnCloseCallback",
    "OnConnect",
    "OnDisconnect",
    "OnMessageHandler",
    "Options",
    "OutgoingContext",
    "OutgoingHandler",
    "PondAssigns",
    "PondError",
    "PondMessage",
    "PondPresence",
    "PondSocket",
    "PresenceClient",
    "PresenceEventTypes",
    "PubSub",
    "PubSubClosedError",
    "PushableTransport",
    "RateLimiter",
    "RecipientSpec",
    "Route",
    "SSEServerTransport",
    "ServerActions",
    "Store",
    "SystemEntity",
    "SystemEvents",
    "ToUsers",
    "TokenBucketRateLimiter",
    "Transport",
    "TransportType",
    "TypedChannel",
    "TypedEventContext",
    "TypedEventHandler",
    "TypedJoinContext",
    "TypedJoinHandler",
    "TypedLobby",
    "User",
    "UserData",
    "__version__",
    "bad_request",
    "conflict",
    "error_event",
    "event_to_json",
    "event_to_pubsub_bytes",
    "event_to_wire",
    "forbidden",
    "format_heartbeat_topic",
    "format_message_topic",
    "format_presence_topic",
    "format_system_topic",
    "format_topic",
    "internal",
    "match_topic",
    "not_found",
    "parse",
    "parse_inbound_text",
    "pubsub_bytes_to_event",
    "too_many_requests",
    "typed_lobby",
    "unauthorized",
    "uuid",
    "wire_to_event",
    "with_metrics",
    "with_rate_limiter",
]
