from __future__ import annotations

from collections.abc import Awaitable, Callable
from typing import Any, Protocol, TypeAlias, runtime_checkable

from .types import Event, TransportType

OnCloseCallback: TypeAlias = Callable[["Transport"], Awaitable[None]]
OnMessageHandler: TypeAlias = Callable[[Event, "Transport"], Awaitable[None]]


@runtime_checkable
class Transport(Protocol):
    def get_id(self) -> str: ...
    async def send_event(self, event: Event) -> None: ...
    def get_assign(self, key: str) -> Any: ...
    def set_assign(self, key: str, value: Any) -> None: ...
    def clone_assigns(self) -> dict[str, Any]: ...
    def is_active(self) -> bool: ...
    async def close(self) -> None: ...
    def on_close(self, callback: OnCloseCallback) -> None: ...
    def on_message(self, handler: OnMessageHandler) -> None: ...
    async def handle_messages(self) -> None: ...
    def transport_type(self) -> TransportType: ...


@runtime_checkable
class PushableTransport(Transport, Protocol):
    async def push_message(self, data: bytes) -> None: ...
