from __future__ import annotations

from importlib.metadata import PackageNotFoundError, version

from .enums import (
    ChannelReceiver,
    ChannelState,
    ClientActions,
    ErrorTypes,
    Events,
    PresenceEventTypes,
    PubSubEvents,
    ServerActions,
    SystemSender,
)
from .errors import (
    STATUS_BAD_REQUEST,
    STATUS_CONFLICT,
    STATUS_FORBIDDEN,
    STATUS_GATEWAY_TIMEOUT,
    STATUS_INTERNAL_SERVER_ERROR,
    STATUS_NOT_FOUND,
    STATUS_SERVICE_UNAVAILABLE,
    STATUS_TOO_MANY_REQUESTS,
    STATUS_UNAUTHORIZED,
    MultiError,
    PondError,
    add_error,
    bad_request,
    combine,
    conflict,
    forbidden,
    internal,
    not_found,
    temporary_error,
    timeout,
    too_many_requests,
    unauthorized,
    unavailable,
    wrap,
)
from .headers import Headers, RawHeader, RawHeaders
from .ids import uuid
from .schema import (
    PondEvent,
    PondSchema,
    TypedPresencePayload,
    from_pond_object,
    pond_event,
    pond_schema,
    to_pond_object,
)
from .schemas import (
    ChannelEvent,
    ClientMessage,
    PresenceMessage,
    PresencePayloadModel,
    ServerMessage,
    ServerMessageAction,
    ValidationError,
    parse_channel_event,
    parse_client_message,
    parse_presence_message,
    parse_server_message,
)
from .subjects import BehaviorSubject, Subject
from .types import (
    ChannelReceivers,
    IncomingConnection,
    JoinParams,
    PondAssigns,
    PondMessage,
    PondObject,
    PondPresence,
    PresencePayload,
    PubSubEvent,
    PubSubGetPresenceCommand,
    PubSubMessageEvent,
    PubSubPresenceEvent,
    Subscriber,
    Unsubscribe,
    UserAssigns,
    UserData,
    UserPresences,
)

try:
    __version__ = version("pondsocket-common")
except PackageNotFoundError:
    __version__ = "0.0.1"

__all__ = [
    "STATUS_BAD_REQUEST",
    "STATUS_CONFLICT",
    "STATUS_FORBIDDEN",
    "STATUS_GATEWAY_TIMEOUT",
    "STATUS_INTERNAL_SERVER_ERROR",
    "STATUS_NOT_FOUND",
    "STATUS_SERVICE_UNAVAILABLE",
    "STATUS_TOO_MANY_REQUESTS",
    "STATUS_UNAUTHORIZED",
    "BehaviorSubject",
    "ChannelEvent",
    "ChannelReceiver",
    "ChannelReceivers",
    "ChannelState",
    "ClientActions",
    "ClientMessage",
    "ErrorTypes",
    "Events",
    "Headers",
    "IncomingConnection",
    "JoinParams",
    "MultiError",
    "PondAssigns",
    "PondError",
    "PondEvent",
    "PondMessage",
    "PondObject",
    "PondPresence",
    "PondSchema",
    "PresenceEventTypes",
    "PresenceMessage",
    "PresencePayload",
    "PresencePayloadModel",
    "PubSubEvent",
    "PubSubEvents",
    "PubSubGetPresenceCommand",
    "PubSubMessageEvent",
    "PubSubPresenceEvent",
    "RawHeader",
    "RawHeaders",
    "ServerActions",
    "ServerMessage",
    "ServerMessageAction",
    "Subject",
    "Subscriber",
    "SystemSender",
    "TypedPresencePayload",
    "Unsubscribe",
    "UserAssigns",
    "UserData",
    "UserPresences",
    "ValidationError",
    "__version__",
    "add_error",
    "bad_request",
    "combine",
    "conflict",
    "forbidden",
    "from_pond_object",
    "internal",
    "not_found",
    "parse_channel_event",
    "parse_client_message",
    "parse_presence_message",
    "parse_server_message",
    "pond_event",
    "pond_schema",
    "temporary_error",
    "timeout",
    "to_pond_object",
    "too_many_requests",
    "unauthorized",
    "unavailable",
    "uuid",
    "wrap",
]
