from __future__ import annotations

from enum import StrEnum


class PresenceEventTypes(StrEnum):
    JOIN = "JOIN"
    LEAVE = "LEAVE"
    UPDATE = "UPDATE"


class ServerActions(StrEnum):
    PRESENCE = "PRESENCE"
    SYSTEM = "SYSTEM"
    BROADCAST = "BROADCAST"
    ERROR = "ERROR"
    CONNECT = "CONNECT"


class ClientActions(StrEnum):
    JOIN_CHANNEL = "JOIN_CHANNEL"
    LEAVE_CHANNEL = "LEAVE_CHANNEL"
    BROADCAST = "BROADCAST"


class ChannelState(StrEnum):
    IDLE = "IDLE"
    JOINING = "JOINING"
    JOINED = "JOINED"
    STALLED = "STALLED"
    CLOSED = "CLOSED"
    DECLINED = "DECLINED"


class ErrorTypes(StrEnum):
    UNAUTHORIZED_CONNECTION = "UNAUTHORIZED_CONNECTION"
    UNAUTHORIZED_JOIN_REQUEST = "UNAUTHORIZED_JOIN_REQUEST"
    UNAUTHORIZED_BROADCAST = "UNAUTHORIZED_BROADCAST"
    INVALID_MESSAGE = "INVALID_MESSAGE"
    HANDLER_NOT_FOUND = "HANDLER_NOT_FOUND"
    PRESENCE_ERROR = "PRESENCE_ERROR"
    CHANNEL_ERROR = "CHANNEL_ERROR"
    ENDPOINT_ERROR = "ENDPOINT_ERROR"
    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"


class SystemSender(StrEnum):
    ENDPOINT = "ENDPOINT"
    CHANNEL = "CHANNEL"


class ChannelReceiver(StrEnum):
    ALL_USERS = "ALL_USERS"
    ALL_EXCEPT_SENDER = "ALL_EXCEPT_SENDER"


class Events(StrEnum):
    ACKNOWLEDGE = "ACKNOWLEDGE"
    CONNECTION = "CONNECTION"
    NOT_FOUND = "NOT_FOUND"
    UNAUTHORIZED = "UNAUTHORIZED"


class PubSubEvents(StrEnum):
    MESSAGE = "MESSAGE"
    PRESENCE = "PRESENCE"
    GET_PRESENCE = "GET_PRESENCE"
