export enum PresenceEventTypes {
    JOIN = 'JOIN',
    LEAVE = 'LEAVE',
    UPDATE = 'UPDATE'
}

export enum ServerActions {
    PRESENCE = 'PRESENCE',
    SYSTEM = 'SYSTEM',
    BROADCAST = 'BROADCAST',
    ERROR = 'ERROR',
}

export enum ClientActions {
    JOIN_CHANNEL = 'JOIN_CHANNEL',
    LEAVE_CHANNEL = 'LEAVE_CHANNEL',
    BROADCAST = 'BROADCAST',
}

export enum PondState {
    CONNECTING = 'CONNECTING',
    OPEN = 'OPEN',
    CLOSING = 'CLOSING',
    CLOSED = 'CLOSED',
}

export enum ChannelState {
    IDLE = 'IDLE',
    JOINING = 'JOINING',
    JOINED = 'JOINED',
    STALLED = 'STALLED',
    CLOSED = 'CLOSED',
}

export enum ErrorTypes {
    UNAUTHORIZED_JOIN_REQUEST = 'UNAUTHORIZED_JOIN_REQUEST',
    UNAUTHORIZED_BROADCAST = 'UNAUTHORIZED_BROADCAST',
    INVALID_MESSAGE = 'INVALID_MESSAGE',
    HANDLER_NOT_FOUND = 'HANDLER_NOT_FOUND',
    PRESENCE_LEAVE_FAILED = 'PRESENCE_LEAVE_FAILED',
    INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
}

export enum SystemSender {
    SERVER = 'SERVER',
    ENDPOINT = 'ENDPOINT',
    CHANNEL = 'CHANNEL',
}
